// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SpecimenApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260715124455_UpdateToOneColumn")]
    partial class UpdateToOneColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Tables.Discrepancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManifestId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecimenId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.HasIndex("SpecimenId");

                    b.ToTable("Discrepancies");
                });

            modelBuilder.Entity("Domain.Tables.Lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("Domain.Tables.Manifest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LabId");

                    b.ToTable("Manifests");
                });

            modelBuilder.Entity("Domain.Tables.Specimen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManifestId")
                        .HasColumnType("int");

                    b.Property<string>("Patient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("Specimens");
                });

            modelBuilder.Entity("Domain.Tables.Discrepancy", b =>
                {
                    b.HasOne("Domain.Tables.Manifest", "Manifest")
                        .WithMany("Discrepancies")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Tables.Specimen", "Specimen")
                        .WithMany("Discrepancies")
                        .HasForeignKey("SpecimenId");

                    b.Navigation("Manifest");

                    b.Navigation("Specimen");
                });

            modelBuilder.Entity("Domain.Tables.Manifest", b =>
                {
                    b.HasOne("Domain.Tables.Lab", "Lab")
                        .WithMany("Manifests")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("Domain.Tables.Specimen", b =>
                {
                    b.HasOne("Domain.Tables.Manifest", "Manifest")
                        .WithMany("Specimens")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("Domain.Tables.Lab", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("Domain.Tables.Manifest", b =>
                {
                    b.Navigation("Discrepancies");

                    b.Navigation("Specimens");
                });

            modelBuilder.Entity("Domain.Tables.Specimen", b =>
                {
                    b.Navigation("Discrepancies");
                });
#pragma warning restore 612, 618
        }
    }
}
